config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :projects

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asign.rb
class Asign < ApplicationRecord
end

app/models/member.rb
class Member < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    def index
      @projects = Project.all
    end

    def show
      @project = Project.find(params[:id])
    end

    def new
     @project = Project.new
    end

    def create
      @project = Project.new(project_params)
      if @project.save
        redirect_to projects_url
      else
      end
    end

    def edit  
      @project = Project.find(params[:id])
    end

    def update
      @project = Project.find(params[:id])
      if @project.update(project_params)
        render :show
      else
      end
    end

    def destroy
      Project.find(params[:id]).destroy!
      redirect_to projects_url
    end

    def project_params
      params.require(:project).permit(:title,:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MisterToDo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/edit.html.erb
<h1>プロジェクトへんしゅー</h1>
<%= render partial: "shared/common_form" ,locals: {project: @project} %>

app/views/projects/index.html.erb
<h1>projectのいちらん。</h1>
<h3><%= link_to "New", new_project_path %></h3>


<% @projects.each do |project|%>
  <ul>
    <%= link_to project.title, project_path(project) %>
  </ul>
<% end %>

app/views/projects/new.html.erb
<h1>プロジェクト登録</h1>
<%= render partial: "shared/common_form" ,locals: {project: @project} %>

app/views/projects/show.html.erb
<h1>deteil</h1>
<ul>
  <h3><%= @project.title %></h3>
  <p><%= @project.content %></p>
</ul>
<%= link_to 'Edit', edit_project_path(@project)%>
<%= link_to 'Delete', project_path(@project), method: :delete, data: { confirm: "削除してもよろしいですか？" }%>
<%= link_to 'Index', projects_path%>

app/views/shared/_common_form.erb
<%= form_for @project do |f|%>
<p>
  <%= f.label :title %>
  <%= f.text_field :title%>
</p>
<p>
  <%= f.label :content %>
  <%= f.text_field :content%>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>